// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"


@interface Root : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

